name: CI/CD Workflow

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      run: |
        docker build -t your-docker-image-name .     
        docker push your-docker-image-name

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Docker
      run: |
        docker pull your-docker-image-name
        docker run -d -p 8080:80 -v $(pwd):/app your-docker-image-name
